# alacritty.toml
# By OldJobobo (https://github.com/OldJobobo)
# 


[colors]
[colors.primary]
background = "#1e1e1e"
foreground = "#ffffff"

[colors.normal]
black   = "#1e1e1e"
red     = "#cf6a4c"
green   = "#8f9d6a"
yellow  = "#f9ee98"
blue    = "#7587a6"
magenta = "#9b859d"
cyan    = "#afc4db"
white   = "#a7a7a7"

[colors.bright]
black   = "#5f5a60"
red     = "#cf6a4c"
green   = "#8f9d6a"
yellow  = "#f9ee98"
blue    = "#7587a6"
magenta = "#9b859d"
cyan    = "#afc4db"
white   = "#ffffff"

[colors.cursor]
text   = "#1e1e1e"
cursor = "#ffffff"

#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#
